/**
 * 
 */
package com.adatao.ddf.content;

import java.util.Enumeration;

import com.adatao.ddf.etl.IHandleFilteringAndProjections;

/**
 * <p>
 * Views are different, but related DDFs. A new view may be generated by some transformation
 * of an existing DDF, by, e.g., {@link IHandleFilteringAndProjections},
 * which results in entirely new DDFs with different columns or rows. 
 * </p>
 * <p>
 * Views should be implemented as weak or soft references from the original DDF. The intent is to have
 * these views "cached", so that they can stick around a bit after creation, in case the same
 * machine-learning algorithm is called requiring the same view. At the same time, because they
 * are weak references, they can be garbage collected soon, thus saving memory.
 * </p>
 * 
 * @author ctn
 * 
 */
public interface IHandleViews {
  public Object get(int[] xCols, int[] yCols, Enumeration<Integer> format);

  /**
   * Clears out all current views.
   */
  public void reset();

  /**
   * Adds a view to the set of existing views.
   * 
   * @param rows
   * @param containerType
   * @param elementType
   */
  public void add(Object data, int[] xCols, int[] yCols, Enumeration<Integer> format);

  /**
   * Removes a representation from the set of existing representations.
   * 
   * @param containerType
   * @param elementType
   */
  public void remove(Enumeration<Integer> format);
}
